POST http://localhost:5000/iam/auth/create-superadmin HTTP/1.1
content-type: application/json

{
    "appid": "digitalinventory",
    "userid": "jsthtet96@gmail.com",
    "password": "P@ssword",
    "username": "John Satieer",
    "companyid": "techhype",
    "companyname": "techhype",
    "otpservice": "email",
    "profile": ""
}

