POST http://150.95.82.125/iam/auth/create-superadmin HTTP/1.1
content-type: application/json

{
    "appid": "juice",
    "userid": "admin",
    "password": "P@ssword",
    "username": "Admin",
    "companyid": "techhype",
    "companyname": "techhype",
    "otpservice": "none",
    "profile": "",
    "mobile": "09404888722"
}

